//
// Created by radu on 12/7/18.
//

#ifndef REMMUX_CONSTANTS_H
#define REMMUX_CONSTANTS_H

#define PIPE_READ 0
#define PIPE_WRITE 1

#define REAL_CONSOLE_H 59
#define REAL_CONSOLE_W 220
#define CONSOLE_H 59
#define CONSOLE_W 220
#define MAX_WINDOWS 25

#define BUFFER_SIZE 10240

#define PROTOCOL_INITIATE_SHUTDOWN 0
#define PROTOCOL_HEARTBEAT 1
#define PROTOCOL_CREATE_SESSION 2
#define PROTOCOL_STREAM 3

#endif //REMMUX_CONSTANTS_H
